spring:
  config:
    import: classpath:application-secret.properties
  application:
    name: social-network

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:

    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            client-id: "id"
            client-secret: "secret"
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            client-id: "id"
            client-secret: "secret"
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
# JWT config
security:
  jwt:
    access:
      expired: 5
      key: ${ACCESS_KEY}
    refresh:
      expired: 14
      key: ${REFRESH_KEY}

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_KEY}
  api-secret: ${CLOUD_SECRET}